### ISSUE TITLE
Positionsabfrage für den Ball im Spiel Pong

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/Prima#1]
Gibt es eine Möglichkeit die aktuelle Position des Balles bezogen auf das Canvas abzufragen? 

```html
<canvas width="600" height="400"></canvas>
```
```typescript
(if ball.position.x > canvas.width) {
  //do something
}
``` 

Ich habe leider dazu auch nichts im Fudge Core gefunden. 

Ich möchte dadurch eine Abfrage schreiben die bei Berührung der Kanten des Canvas den Ball in eine andere Richtung ablenken lässt.

**Comment by Hexadezimal** [comment]
Es gibt (noch) keine Möglichkeit, die genaue Position eines Objektes abzufragen. Du kannst höchstens für dich selber in der Console über getMutator() die Positionswerte anzeigen lassen. 

Mein spontaner Lösungsansatz (den ich noch nicht getestet habe) wäre: Eine Variable, die hochzählt während sich der Ball bewegt. Nun müsstest du nur noch eine Möglichkeit finden um mit Hilfe der Startposition, dem Winkel und der Geschwindigkeit festzustellen, bei welchem Wert dieser Variablen der Ball den Rand des Canvas erreicht.

**Comment by benediktgrether** [comment]
Danke für die erklärende Antwort :) dann muss ich mal schauen ob ich bis Dienstag was hin bekomme oder ob wir gemeinsam eine Lösung erarbeiten :)

**Comment by JirkaDellOro** [comment]
Matrix4x4 verfügt über die Getter `translation`, `scaling` und `rotation` mit der sich eben diese Infos ermitteln lassen. Es sind auch gleichnamige Setter implementiert.

Allerdings erhälst Du damit nur die Position im Raum und nicht die Projektion auf den Canvas. Diese ist abhängig von den Kameraeinstellungen. Vielleicht implementieren wir im Viewport oder der Kamera einmal eine Methode zur Projektion eines Punktes. 

Mein Tipp ist nicht nach Bildschirmkoordinaten zu schauen, sondern die Kollisionen im Raum zu betrachten und die Kamera guckt sich das halt auch an...

**Comment by benediktgrether** [comment]
Danke für die nützlichen Hinweise. Über 
```ball.cmpTransform.local.translation.x``` und ```ball.cmpTransform.local.translation.y``` hab ich nun die Position des Balles im Viewport abgefragt.
