### ISSUE TITLE
Versetzen des Sprite-Pivots

### ISSUE THREAD

**Issue by NicoKlein97** [JirkaDellOro/Prima#11]
Heyho, habe eine kleine Frage. Gibt es die Möglichkeit den Pivot meines Charakter-Sprites um wenige Pixel auf der X-Achse zu verschieben ?

**Comment by JirkaDellOro** [comment]
Du kannst für jeder Phase den Pivot verändern, dazu gehst Du das frame-Array des Sprites durch und manipulierst deren pivot-Eigenschaft.

Alternativen:  
-  NodeSprite als Kind einem übergeordneten Knoten anhängen und es dann wie gewünscht verschieben.
- die NodeSprite-Klasse um einen Versatz erweitern und diesen in showFrame addieren

**Comment by NicoKlein97** [comment]
Alles klar, danke.
