### ISSUE TITLE
Allgemeine Fragen zur Abgabe

### ISSUE THREAD

**Issue by AnnaLotz** [JirkaDellOro/Prima#13]
Hallo @JirkaDellOro ,
ich habe ein paar Fragen und Anmerkungen zur Abgabe allgemein.

1. Das Designdokument soll ein PDF sein. Was muss da alles rein? Soll darin die Checkliste abgearbeitet werden (Muss diese also nicht als HTML-Tabelle zur Verfügung stehen wie im letzen Seminar vorgeschlagen)? Und **_müssen_** wir zusätzlich Konzepte wie Diagramme/Zeichnungen dafür erstellen? 

2. Punkt 6 GUI: Dort steht  "_...mit Hilfe von Flash-Komponenten Einstellungen beim Programmstart oder während des Programmlaufs vorzunehmen_". Ich nehme mal an, dass sich die "Flash-Komponenten" fälschlicherweise dort mit eingeschlichen haben. Müssen wir Interaktion in das GUI bringen? Wäre ein "Start"-Knopf oder ähnliches ausreichend?

3. Punkt 7 Externe Daten: Auch hier bin ich mir nicht sicher ob ich das richtig interpretiere. "Neu Starten" im Sinne von Seite neu laden oder neu öffnen? Meint das z.B. Spritesheets, die man ja theoretisch austauschen könnte und das Aussehen bei neuladen des Spiels ändern würde?
Mein Level möchte ich random generieren, daher brauche ich keine Level-Datei. Muss ich mir dann etwas anderes aus den Haaren herbei ziehen um den Punkt zu erfüllen oder sind Bilddateien ausreichen?

4. Punkt 11 Event-System: Reicht hier das erklären der wichtigsten Events für den Spielablauf oder muss jedes noch so kleine Event erläutert werden?

**Comment by JirkaDellOro** [comment]
- Das Designdokument beschreibt das zu produzierende Spiel, auf funktionaler und technischer Ebene. Wie was aus Sicht des Spielers funktionieren soll und wie es technisch umgesetzt werden soll. Es wird also vor der Produktion erstellt. Die Medienkonzepter wissen, wie man das macht.  
- Die Checkliste brauche ich als HTML oder Markdown, ihr könnt sie also direkt aus dem Prima-Repository nehmen und in euer README.md reinkleben und ausfüllen.  
- > Und müssen wir zusätzlich Konzepte wie Diagramme/Zeichnungen dafür erstellen?
Wie sonst? Willst Du damit andeuten, dass Du als Medienkonzepter ohne arbeitest?

- >Wäre ein "Start"-Knopf oder ähnliches ausreichend?  

Das wäre das absolute Minimum.

- > Muss ich mir dann etwas anderes aus den Haaren herbei ziehen um den Punkt zu erfüllen oder sind Bilddateien ausreichen?  

Es muss nicht aus den Haaren sein, aber die Bilddateien sind natürlich keine sinnvolle Anforderung

- > Punkt 11 Event-System: Reicht hier das erklären der wichtigsten Events für den Spielablauf ...

reicht

**Comment by NicoKlein97** [comment]
Ich hätte zum Termin der Abgabe noch eine kleine Frage. Wann genau ist der Abgebetermin?
In den Prüfungsplänen steht der 14.02 drinnen, ich habe aber irgendwie den 17.02 im Kopf. 
So geht es auch noch ein paar anderen, deshalb wollte ich mal nachfragen.

**Comment by Hexadezimal** [comment]
Laut meines Protokolls haben wir auch den 17.02. ausgemacht, aber ohne das mit den Prüfungsplänen abzugleichen. Daher wäre es ganz gut, wenn Jirka angibt, welcher dieser Termine tatsächlich stimmt.

**Comment by JirkaDellOro** [comment]
17. passt für mich
