### ISSUE TITLE
Spiel pausieren

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/Prima#14]
Hallo Jirka und Prima Leute, 

gibt es eine Möglichkeit in FUDGE das Spiel zu pausieren und dann später an der gleichen Stelle wieder zu starten? 

Viele Grüße
Benedikt

**Comment by AnnaLotz** [comment]
Ich habe gerade nach etwas ähnlichem gesucht. Das was du brauchst ist vermutlich `f.Loop.stop` Damit hält die komplette Animation bei mir an. Ich vermute mir f.Loop.start kann man wieder weiter machen? https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/classes/fudgecore.loop.html#stop

**Comment by Hexadezimal** [comment]
Meinst du einen einfachen Pausebildschrim oder ein richtiges Speichern/Laden?

Ersteres kannst du mit der Abfrage eines boolschen Wertes erreichen. Nur wenn z. B. die Variabele "pause" false ist, soll dein Spiel Dinge tun, ansonstne wird einfach "Spiel pausiert" etc. angezeigt.

Letzteres müsstest du mit Hilfe von externen Dateien lösen können. Du müsstest in einer json die Spielerposition, Level, Leben und alle anderen wichtigen Daten speichern und diese dann wenn gewünscht, aus dem json wieder laden.

**Comment by Hexadezimal** [comment]
Ja, f.Loop.stop bzw. start müssten auch möglich sein für eine einfache Pause.

**Comment by benediktgrether** [comment]
Okay danke. Ja es geht darum das Game zu pausieren - Menü das sich öffnet und danach z.B Muten und wieder weiterspielen

**Comment by JirkaDellOro** [comment]
Ein wenig muss man aufpassen, da die Zeit weiter läuft. Startet man die Loop wieder, entsteht ggf. einmalig eine sehr große FrameTime

Folgendes kann man dagegen tun, wenn erforderlich
- auch die Zeit stoppen/starten
- nur die Zeit-Skalierung auf 0 setzen, dann stoppt alles, was Time.game nutzt
- eine eigene Zeit instanzieren, und die Loop darauf laufen lassen, dann diese Zeit stoppen

**Comment by NicoKlein97** [comment]
Das Spiel mithilfe von fudge.loop.stop() anzuhalten und danach mit fudge.loop.start() wieder zu starten hat bei mir nur mit dem auskommentieren von einer Zeile in der fudge.core funktioniert. Das Problem ist, dass  loop.start() automatisch auch die stop() ausführt. In dieser wird dann aber eine deleteTimer-Methode aufgerufen, welche mit einer Loop.idIntervall gefüttert wird. Wenn ich jetzt also zuerst loop.stop() ausführe um ungestört im Menü arbeiten zu können und danach loop.start() benutzen möchte, ruft er die deleteTimer-Methode mit einer Id auf, welche auf ein Timer-Objekt zeigt, das gar nicht mehr existiert und wirft deshalb einen Error. Gibt es also eine Möglichkeit loop.start()/ stop() zu nutzen, ohne in dieses Problem zu rennen?

P.S. Die Zeile, die ich auskommentiert habe, ist der Aufruf von der fudge.loop.stop() in der fudge.loop.start(). Aber das kann ja nicht der Sinn der Sache sein XD

**Comment by JirkaDellOro** [comment]
Ich habe den Eindruck, da fehlte im Loop.stop die Negation von Loop.running. Ich habe das einmal eingefügt, bitte pullen. Das müsste den gleichen Effekt haben wie dein Auskommentieren aber den Sinn der Sache erhalten.
Der war: wenn man eine laufende Loop noch einmal startet, ggf mit anderen Parametern, muss der aktuelle Lauf zunächst gestoppt werden.

**Comment by JirkaDellOro** [comment]
Bitte prüfen und ggf. schließen!
