### ISSUE TITLE
Performance-Probleme durch dynamisch erzeugt Objekte

### ISSUE THREAD

**Issue by plojo** [JirkaDellOro/Prima#15]
Hallo, ich erzeuge in meinem Spiel periodisch neue Objekte, füge sie der Hierarchie hinzu und entferne sie nach kurzer Zeit wieder aus dieser (sie werden Garbage Collected). Das funktioniert auch erstmal problemlos aber je mehr Zeit vergeht desto schlechter wird die Performance des Spiels bis es so gut wie unspielbar ist.
Ich habe hier mal ein minimal Beispiel erstellt von dem was ich mache:
[https://github.com/plojo/PRIMA/tree/master/PerformanceLeak](https://github.com/plojo/PRIMA/tree/master/PerformanceLeak)
[https://plojo.github.io/PRIMA/PerformanceLeak/Main.html](https://plojo.github.io/PRIMA/PerformanceLeak/Main.html)
und es mit Hilfe von CHrome und dem TaskManager untersucht:
Auf der linken Seite befinden sich die Daten kurz nach dem das Spiel gestartet wurde, auf der rechten lief das Spiel für ein paar Minuten. Die Performance-Aufnahme von Chrome ging jeweils 10 Sekunden.
![PerformanceTest](https://user-images.githubusercontent.com/38690628/74606573-d929be80-50d1-11ea-90dc-6afbf4eb6a13.png)

Je länger das Spiel läuft desto rechenintensiver wird das updaten des Viewports und desto langsamer läuft das Spiel...

Nun meine Frage muss ich noch irgendetwas spezielles tun damit meine Ressourcen wieder korrekt freigegeben werden (abgesehen von dem löschen der Referenzen auf meine Objekt)?

Getestet wurde mit einer aktuellen Fudge Version.

**Comment by benediktgrether** [comment]
Entfernst du dabei auch ihre Update funktion falls du den Objekten einen Loop und Update mitgegeben hast ?

`ƒ.Loop.removeEventListener(ƒ.EVENT.LOOP_FRAME, _enemy.update);`

**Comment by plojo** [comment]
> Entfernst du dabei auch ihre update Funktion falls du den Objekten einen Loop und Update mitgegeben hast ?
> 
> `ƒ.Loop.removeEventListener(ƒ.EVENT.LOOP_FRAME, _enemy.update);`

ja in meinem Spiel tue ich das. In dem minimal Beispiel registrieren meine erzeugten Objekte sich aber nicht einmal irgendwo und die Performance geht trotzdem runter.

**Comment by JirkaDellOro** [comment]
Objekterzeugung ist teuer und der Garbage-Collector von Javascript fährt periodisch hart in den Programmablauf. Deswegen gibt es in FUDGE den Recycler, bislang hatten wir noch nicht den Bedarf ihn zu besprechen.

Ich denke aber nicht, dass hier das einzige Problem liegt. Ich schaue mir das gerne an, vielleicht entdecken wir etwas Fundamentales...

**Comment by JirkaDellOro** [comment]
Ich habe mir das näher angeschaut. Ändere mal deinen Code wie folgt und teste dann wieder:

```typescript
        if (game.getChildren().length > 0) {
          let node: ƒ.Node = game.getChildren().pop();
          game.removeChild(node);
          ƒ.RenderManager.removeNode(node);
        }
```

Da geht es genau um die gedoppelte Verwaltung im RenderManager. Lass mich die Ergebnisse wissen.

**Comment by JirkaDellOro** [comment]
So....
Deine Anregung hat mich motiviert, mich dem Umbau des RenderManagers gleich zu widmen. Er ist bereits abgeschlossen, hierzu habe ich entsprechende Issues gepostet. Bitte gerne testen.

Übrigens: im "Performance monitor" von Chrome kann man sehr schön zur Laufzeit die Auslastungen verfolgen ohne Aufzeichnungen machen zu müssen. Das ist sicher hilfreich für dich bei der Arbeit mit Partikelsystemen.
