### ISSUE TITLE
Fehlerbehebung INstallation

### ISSUE THREAD

**Issue by sabinecelina** [JirkaDellOro/Prima#17]
Wenn beim Build Vorgang der Typescript Datei ein Fehler auftaucht: Die Datei "C:\Users\..\AppData\Roaming\npm\tsc.ps1" kann nicht geladen werden, da die Ausführung von Skripts auf diesem System deaktiviert ist.

einfach das in der Powershell als Administrator (Windowstaste + x) (nicht cmd!) eingeben: 

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine

Dann nocheinmal den Build Vorgang starten

**Comment by JirkaDellOro** [comment]
Kann der Issue geschlossen werden?
