### ISSUE TITLE
alfaview Smartphon

### ISSUE THREAD

**Issue by sabinecelina** [JirkaDellOro/Prima#18]
Hallo Jirka, 

du meintest doch, dass du alfaview auch mit dem Smartphone nutzt? Wie hast du das hinbekommen?

**Comment by JirkaDellOro** [comment]
Hallo Sabine,

das machst Du zunächst damit, dass Du dein Smartphone als Webcam anschließt. Dafür gibt es entsprechende Software, z.B. iVCam oder DroidCam. In Alfaview kannst Du es dann als  Zweitkamera aktivieren,

**Comment by JirkaDellOro** [comment]
Kann der Issue geschlossen werden?
