### ISSUE TITLE
Need help catching up with the rest of the class

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#19]
Hey guys. 

Unfortunately I wasn't present during Mr DellOro-Friedl's first class when everyone had set up their cloned repositories in visual studio code. 

Would someone be able to help me with this? I try searching up "git: clone" un the command palette in the "view" tab on vs code but nothing appears. 

Thank you for any help in advance.
I can be reached at Rowan5654@hotmail.com

- Rowan

**Comment by JirkaDellOro** [comment]
Do you have git installed on your system?

**Comment by Rowan5654** [comment]
No, I only have the github addon installed into my visual studio code.

I’ll install it now.


  *   Rowan

**Comment by Nigolilolino** [comment]
@Rowan5654 

In case you still need help:

After downloading git, create a folder somewhere on your PC (This folder will contain your files). Then open that folder in VS Code and open the terminal. Now you need to type: git clone [your repository URL] (you can get that by opening your repo in Github and click on "clone or download"). After using the command, the Repository should be connected with your folder.

**Comment by Rowan5654** [comment]
Thank you so much! This was extremely helpful!


  *   Rowan

________________________________

**Comment by JirkaDellOro** [comment]
You can also hit F1 and type git to see and execute the commands available

**Comment by Rowan5654** [comment]
Awsome! Thank you @Nigolilolino I followed your instruction and I managed to get it set up! :D
