### ISSUE TITLE
Issues setting up typescript!!!

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#20]
Hello. 

I am sure this is probably common knowledge to everyone by now but I have been at this problem all morning and I'm finally ready to ask for help.

I am trying to run any typescript file but whenever I enter the command into the terminal:

"tsc filename.ts" 

I just get the error:

"tsc : The term 'tsc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ tsc --init
+ ~~~
    + CategoryInfo          : ObjectNotFound: (tsc:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

I have tried running the "npm install -g typescript" command because I thought that I needed to install typescript even though it should have come with vscode but I just get the same error. 

Anyone see my problem here? I'm very new to vscode as I usually use vsstudio and notepad++ so perhaps I've done something wrong here during installation?

Thanks.

- Rowan
![Issue](https://user-images.githubusercontent.com/53504428/80572586-cf400800-89fe-11ea-8c5d-7a6f79f6efa5.PNG)

**Comment by JirkaDellOro** [comment]
"npm install -g typescript"

That should do it, right. Restarted computer?

**Comment by Rowan5654** [comment]
When I type that in I get the same message as before.

Perhaps I have set up visual studio code incorrectly? Is there any external software I need to download I don't know about?

![image](https://user-images.githubusercontent.com/53504428/80591352-dcb8ba80-8a1d-11ea-8a4d-f550c13101e5.png)

**Comment by JirkaDellOro** [comment]
Ah... your system doen't even know npm, so installing typescript didn't work in the first place. Of course, then you can't call tsc...
So install Node.js, which usually comes with VSCode

**Comment by JirkaDellOro** [comment]
Please leave a final comment with some explanation to the solution you found, so that we all can learn from it.

**Comment by Rowan5654** [comment]
I'm not really sure what I did to get it working. I just turned my computer off and went to bed. When I woke up this morning it miraculously worked! 

Perhaps my solution was to restart my computer? Maybe.

**Comment by JirkaDellOro** [comment]
Maybe it just needed some sleep
