### ISSUE TITLE
alte Links im Readme

### ISSUE THREAD

**Issue by AnnaLotz** [JirkaDellOro/Prima#23]
Hallo Jirka,

die Links zu den lauffähigen Versionen von Pong und Craftris aus dem letzten Semester sind nicht mehr aktuell. Das kommt vermutlich durchs Umsortieren in einen eigenen Ordner fürs WS19 :)

**Comment by JirkaDellOro** [comment]
Danke für den Hinweis. Wie kommt's dass Du bei PRIMA reinschaust?

**Comment by AnnaLotz** [comment]
Bekomme noch Nachrichten, wenn hier ein Issue gepostet wird und habe dann zufällig mal rein geschaut.
