### ISSUE TITLE
Enumeration KEYBOARD_CODE Syntax

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#24]
Hello.

I'm trying to use this link 
https://github.com/JirkaDellOro/FUDGE/blob/253acbed/Core/Source/Event/EventKeyboard.ts#L42

to work out the syntax of this code
![image](https://user-images.githubusercontent.com/53504428/80922913-8aaac880-8d80-11ea-9b7d-b6d727b68cd8.png)

But as you can see it's not working. I've tried to use the other side of the = sign and putting "KeyW" or "KeyA" etc into the arguments but it's still telling me it's wrong. 

Anyone else worked this out? If so could you give me the right syntax? Cheers.
- Rowan

**Comment by JirkaDellOro** [comment]
See https://www.typescriptlang.org/docs/handbook/enums.html to learn how to use enums

**Comment by Rowan5654** [comment]
Ok so I tried the syntax shown in the link you sent me and it DOES recognize the Enumeration because it will tell me it's value. However when I put it into the functions argument I get the error:

![image](https://user-images.githubusercontent.com/53504428/80945034-2ec95980-8deb-11ea-9ae5-14fc36a5cb65.png)

I don't understand. I've done it exactly as it says to do in the link. I just need an example of someone doing it right without an error message. 

Cheers.
- Rowan

**Comment by JirkaDellOro** [comment]
Well the message explicitly tells what the problem is. An array is expected and the documentation for `isPressedOne` tells you why.

**Comment by Rowan5654** [comment]
Alright. Got it working. Just had to add an array instead of a variable that should be inside the array.
