### ISSUE TITLE
Rendering nodes

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#29]
Hey guys, 

So I have been trying to get the cube I'm using as the snakes food to appear in my viewport but I'm sort of lost as to why it's not appearing. I have created the node and I have added a component mesh, a component material and a component transformation but when I run my code only the snake appears and not the food. 

Does this have something to do with having to initialize the Snake AND the snakes food using "viewport.initialize"? In my case the snake and it's food are two separate classes.

Thanks
- Rowan

**Comment by JirkaDellOro** [comment]
Since you didn't post links, neither to code nor to the app, I can only guess around a bit. You initialize the viewport with the graph you want to display. Is the food in the graph?
