### ISSUE TITLE
Fudge aid module documentation

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#31]
Does anyone know where I can find the documentation to the FudgeAid module the same way the FudgeCore module has:
https://jirkadelloro.github.io/FUDGE/Documentation/Reference/Core/modules/fudgecore.html

I'm trying to work out what the function "ƒAid.addStandardLightComponents" does.

Thanks 
- Rowan

**Comment by JirkaDellOro** [comment]
I did some updates. You find what you are looking for here: https://jirkadelloro.github.io/FUDGE/Documentation/Reference/

**Comment by Rowan5654** [comment]
yes! perfect. Thank you Jirka.
