### ISSUE TITLE
Shooting on mouse click

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#34]
So I am trying to make a bullet (Node) spawn in when I left click on my mouse.

![image](https://user-images.githubusercontent.com/53504428/86517176-2ca16c80-be27-11ea-932c-4a7655a38a8c.png)

I think I've got the right class, that being the EventPointer, I have no idea what I'm supposed to give it for it's second argument. 

It says it needs another EventPointer but whatever I give it gives me an error. If I try pass it the "mouse" variable it tells me I can't use it because it's already been declared. What am I doing wrong?

- Rowan

**Comment by JirkaDellOro** [comment]
You didn't grok the concept, I'm afraid. 

- See https://github.com/JirkaDellOro/FUDGE/wiki/Eventsystem first
- Then checkout the most simple test https://jirkadelloro.github.io/FUDGE/Test/Events/ScreenPoint/Test.html

**Comment by Rowan5654** [comment]
I'm still a bit confused by where I'm supposed to put the event listener. Should it go in the main.js? Or can it go in the constructor of the Node? 

![image](https://user-images.githubusercontent.com/53504428/86518750-0f26cf80-be34-11ea-83ad-df052e39d8ef.png)

I have it here working and giving no errors in my player node but when I click I receive no response from the event listener. no bullet appears.

**Comment by JirkaDellOro** [comment]
Post links to the application and the code, please

**Comment by Rowan5654** [comment]
https://github.com/Rowan5654/Prototyping-interactive-Media-Applications-and-Games-

This is a link to just a folder containing my code.

**Comment by JirkaDellOro** [comment]
Post links to the application and the code, please

**Comment by Rowan5654** [comment]
Ok so I went into the source .ts file of your test application link and studied how events were created and called upon. Then related that information into my own program and with a bit of persistence, got it working. :)

**Comment by JirkaDellOro** [comment]
And all I needed to do was post the request for the application twice. Do you know how you would do that?

**Comment by Rowan5654** [comment]
No I wasn't sure what you meant by "application". All I had was my html file which runs my code.

**Comment by JirkaDellOro** [comment]
I mean a link I click on and immediately see your application running in my browser. Look up Github-Pages if you don't know how to do that.
