### ISSUE TITLE
Probleme beim Anwenden des SpriteSheetAnimation Objekts

### ISSUE THREAD

**Issue by Flombo** [JirkaDellOro/Prima#35]
Hallo Jirka,

ich habe Probleme beim Verwenden des SpriteSheetAnimation Objekts.
Ich möchte alle Sprites in das Objekt laden, um später per Frameindex diese abrufen zu können.
Im Spiel selber wird zwischen zwei Frames hin und her gewechselt, obwohl ich die Methode showFrame verwende.
Auch habe ich Probleme die Kamera auf das Objekt richtig zu richten.

Das ist meine Spieler Klasse : https://github.com/Flombo/doomClone/blob/master/GameAssets/Player.ts
Ab Zeile 131 beginnt die Methode zum Initialisieren des Objekts.
Ab Zeile 155 beginnt die Initialisierungsmethode der Kamera.
Das ist das Spritesheet für die Frames : https://github.com/Flombo/doomClone/blob/master/spritesheets/faceSprites.png

Ist mein Ansatz an sich vielleicht falsch?

**Comment by JirkaDellOro** [comment]
Du hast zwar noch kein Issue geschrieben, aber der Audiowechsel sollte jetzt funktionieren. Gerne testen...

**Comment by Flombo** [comment]
Sorry das habe ich vergessen mit aufzuführen.
Der Audiowechsel funktioniert, vielen Dank.

**Comment by JirkaDellOro** [comment]
Ich habe deinen Code nicht näher untersucht, sondern zunächst einfach, auch um selbst zu üben, das Portrait mal als eigentständiges Programm gebaut. Ich habe allerdings deine Generierungszeilen komplett kopiert. Lediglich den Pivot habe ich ins Zentrum des Portraits geschoben. Es hat auf Anhieb funktioniert und der Code liegt als L14 in Prima. Vielleicht kannst Du damit deinen eigenen Fehler finden? Ansonsten bitte hier nachposten...
 
Ich kann mir vorstellen, dass Du einen in NodeSprite die Möglichkeit brauchen könntest, die Animation zu stoppen, so dass sie nicht ständig weiter läuft. Das solltest Du mit setFrameDirection(0) erreichen können.

**Comment by Flombo** [comment]
Das Beispiel funktioniert sehr gut, ich kann nun mit der showFrame Methode die eingeladenen Frames aufrufen.
Der Fehler, welcher die Perspektive verzerrt hat im PortraitViewport, war das Aktivieren von Antialiasing im Rendermanager.
Danke für die Hilfe.

**Comment by JirkaDellOro** [comment]
Antialiasing sollte keinen Fehler provozieren. Wie kommst Du zu dieser Erkenntnis und kannst Du das bitte nochmal überprüfen?

**Comment by Flombo** [comment]
Ich habe die Zeile auskommentiert, in der das Antialiasing und das Freischalten vom Alphakanal geschieht. Nachdem ich das getan habe, funktioniert das Beispiel. Auch hat sich ein anderes Problem gelöst, in dem die quadratischen Projektile eher pfeilförmig, als kubisch dargestellt wurden. Wie könnte ich das genauer Überprüfen ?

**Comment by JirkaDellOro** [comment]
Brauchst Du nicht mehr, jetzt weiß ich, was passiert ist. Du solltest diesen RenderManager.initialize nicht mehr in deinem Code aufrufen, darauf hatte ich vor einiger Zeit in Prima bereits hingewiesen. Er wird mittlerweile beim Start von FUDGE automatisch initialisiert. Wenn Du ihn darauf nochmal initialisierst, zerschießt Du bereits initialisiertes....

Wenn Du antialiasing oder alpha manipulieren willst, machst Du das durch eine Konfigurationszeile in HTML vor dem Laden von FUDGE

`  <script>FudgeCore = {fudgeConfig: {antialias: true, alpha: true}}</script> `

**Comment by Flombo** [comment]
Achso, das war mir nicht mehr bewusst, dann änder ich das so um.
Vielen Dank nochmal.

**Comment by JirkaDellOro** [comment]
Bitte Issue schließen wenn fertig
