### ISSUE TITLE
Continuously running a pointer event

### ISSUE THREAD

**Issue by Rowan5654** [JirkaDellOro/Prima#36]
I'm trying to create a bullet object every time the loop_frame event is called. However, the function that creates the bullet object requires me to have a pointer_event as an argument. I'm not sure how I'm supposed to get one of the updated mouse position.

![image](https://user-images.githubusercontent.com/53504428/86931996-10f4d980-c139-11ea-8b8b-ead999577112.png)

How can I do this?

- Rowan

**Comment by JirkaDellOro** [comment]
First
- implement a globale variable to reference you player-object
- if you already have a list of bullet objects, there is no need to fetch them from the graph by name. So don't.

Then
- if you don't want bullet creation as part of a mouse-event-handler, don't implement it as such. 
- in the eventhandler, determine the world position to shoot at, as discussed in the course
- use that position for the creation of your bullets

**Comment by Rowan5654** [comment]
For some strange reason I can't seem to set my player as a global variable. When I do I just get the message 

"Player is not a constructor" 

![image](https://user-images.githubusercontent.com/53504428/86948744-e5301e80-c14d-11ea-8ed8-7133773ce57c.png)

but I have it right here

![image](https://user-images.githubusercontent.com/53504428/86948773-f11be080-c14d-11ea-8521-a16bb7ae4b58.png)

![image](https://user-images.githubusercontent.com/53504428/86948797-fbd67580-c14d-11ea-8fee-15fddfd30187.png)

I've added it's js file into my html. Is there any other reason this particular error message should be appearing.

- Rowan

**Comment by JirkaDellOro** [comment]
Since you keep failing on providing me with links to your code and to your application I can only guess: separate declaration from definition.

**Comment by Rowan5654** [comment]
Alright. I FINALLY worked out how to get my project to run as an application
https://rowan5654.github.io/shooty-tower/
here is the application

and here is the code repository 
https://github.com/Rowan5654/shooty-tower.git

hopefully this is enough to help you, help me with my problem.
