### ISSUE TITLE
Serializer registriert undefinierten Namespace bei Programmstart 

### ISSUE THREAD

**Issue by Robin-Sb** [JirkaDellOro/Prima#37]
Ich hatte beim Testen des Serializers von fudge das folgende Problem:

Beim Starten meiner Anwendung wird sofort die registerNamespace-Methode des Serializers mit einem Namespace der undefined ist aufgerufen. In der darauffolgenden findNamespaceIn-Methode wird dann "opener" zurückgegeben (weil opener null und _namespace undefined ist returned _parent[prop] = _namespace true), welcher dem Namespaces-Dict hinzugefügt wird. Da der Namespace jedoch undefined ist, wirft die Zeile  
"let found: General = (<General>Serializer.namespaces)[namespaceName][typeName];" 
in der getFullPath-Methode einen Error, weil undefined ja kein typeName-Attribut hat.

Eine mögliche Lösung wäre wohl zu checken ob der _namespace-Parameter undefined ist, aber ich konnte auch nicht rausfinden, wieso die registerNamespace-Methode überhaupt aufgerufen wird
Hier ist der Link zu meinem reduzierten Beispiel: [https://robin-sb.github.io/Editor_Showcase/src/Main.html](https://robin-sb.github.io/Editor_Showcase/src/Main.html)
und hier der Code: [https://github.com/Robin-Sb/Editor_Showcase/tree/master/src](https://github.com/Robin-Sb/Editor_Showcase/tree/master/src)

Hier ist außerdem ein Screenshot von meinem Problem aus dem Debugger:
![image](https://user-images.githubusercontent.com/34275205/87202755-7e536680-c301-11ea-8066-a2ab899740c5.png)

**Comment by JirkaDellOro** [comment]
Wenn ich dein reduziertes Beispiel starte, erhalte ich keine Fehlermeldung. Wie kann ich das Problem reproduzieren?

**Comment by Robin-Sb** [comment]
Ich habe das Beispiel nochmal etwas angepasst, sodass wirklich eine Fehlermeldung ausgegeben wird. Das habe ich beim Aufräumen vergessen zu kopieren. 

Wirklich sieht man den Fehler aber wohl, wenn man in die registerNamespace-Methode einen Breakpoint setzt.

**Comment by JirkaDellOro** [comment]
Vergleiche mal unsere tsconfigs, vielleicht klemmt da was. Mein Resource-Test läuft noch wie erwartet:
FUDGE/Test/Resources/NodeResource/Test.html

**Comment by Robin-Sb** [comment]
Ich habe einfach mal die tsconfig aus deinen Tests kopiert (mit einer ähnlichen Ordnerstruktur) und bekomme immer noch den gleichen Fehler.

Davon abgesehen sollte meiner Meinung nach aber auch kein zufälliger Namespace aus window der null ist hinzugefügt werden, wenn die registerNamespace-Methode mit undefined als Parameter aufgerufen wird, sondern eben ein Error geworfen werden oder vielleicht auch einfach mit warning returnen.

**Comment by Robin-Sb** [comment]
Ich habe mal etwas rumprobiert: 
Der Fehler kommt auf jeden Fall von Zeile 5 von FudgeAid:
`ƒ.Serializer.registerNamespace(ƒAid);`
Im Debugger wird ƒAid auch als undefined angezeigt und wenn ich die Zeile auskommentiere funktioniert alles. Ich bin mir aber nicht ganz sicher wieso ƒAid undefined ist, ich hatte das einfach aus dem Fudge-Repository kopiert, hätte ich das vielleicht noch irgendwie einbinden müssen? Funktionen aus ƒAid wie ƒAid.Node() funktionieren auch in meinem Projekt.

**Comment by JirkaDellOro** [comment]
Sehr gut, da sind wir einen guten Schritt weiter. Durch die Einbindung von Aid in meinen Test kann ich den Fehler reproduzieren und untersuchen!

**Comment by JirkaDellOro** [comment]
Der Namespace wurde registriert bevor er definiert ist. Bitte jetzt probieren.

**Comment by Robin-Sb** [comment]
Die Änderung hat das Problem behoben.

Danke!

**Comment by JirkaDellOro** [comment]
Merke: mit Fehlerbehandlung vorsichtig sein, manchmal verschleiert man sich dadurch den Blick auf die eigentlichen Probleme.
