### ISSUE TITLE
SpriteGenerator

### ISSUE THREAD

**Issue by sabinecelina** [JirkaDellOro/Prima#40]
Hallo Jirka, 

ich will  für mein Spiel nun mit den Sprites arbeiten, aber das Beispiel, das du mit uns durchgegangen bist, hat nun einige Fehler? Also eigentlich nur die Klasse SpriteGenerator, bei denen es die Probleme wirft: (ist in WS19 Ordner in L14). Gibt es ein aktuelleres Beispiel?
![image](https://user-images.githubusercontent.com/45167220/88663036-2ecfb180-d0db-11ea-86fc-e6d306fd8452.png)

**Comment by JirkaDellOro** [comment]
Ja klar:: L12_Plattformer2D in diesem Semester

**Comment by sabinecelina** [comment]
Hallo Jirka, 

wenn ich das debugge siehts bei mir so aus: 

![image](https://user-images.githubusercontent.com/45167220/88778411-c8a16800-d188-11ea-8922-1ab9d2543bab.png)

Weisst du woher der Fehler kommt?

**Comment by sabinecelina** [comment]
Es sieht aber auch so aus, wenn ich nicht debugge und noch deine Version nehme.

**Comment by JirkaDellOro** [comment]
Hast Du mit einem lokalen Server gestartet?

**Comment by sabinecelina** [comment]
Hey jirka, können wir das morgen über alfaview klären? Ich hab vieles versucht, aber nichts hat funktioniert, das hält mich aber davon ab weiterzucoden.

**Comment by sabinecelina** [comment]
Aber ja, ich habs lokal gestartet

**Comment by JirkaDellOro** [comment]
Ich meine lokaler Server, also http://localhost

**Comment by JirkaDellOro** [comment]
Wir können auch auf Alfaview gehen, von mir aus so um 15.00 Uhr

**Comment by sabinecelina** [comment]
Ja, 15 Uhr ist gut.!

**Comment by sabinecelina** [comment]
Nein, ich hab einfach nur die HTML Datei in den Browser verschoben.

**Comment by JirkaDellOro** [comment]
Treffen oder nicht? Ich warte gerade....

**Comment by sabinecelina** [comment]
ich wrte auch, in deinem raum? 


Am Donnerstag, Juli 30, 2020 15:06 CEST, schrieb JirkaDellOro <notifications@github.com>:
 
 
Treffen oder nicht? Ich warte gerade....

**Comment by sabinecelina** [comment]
ja, ich warte gerade im PRIMA raum?

**Comment by sabinecelina** [comment]
Also in DM15

**Comment by JirkaDellOro** [comment]
ach wie doof, ich war in dm16, dem Spiellabor, das ist "mein" Raum...
Besteht das Problem noch?

**Comment by sabinecelina** [comment]
Hey Jirka, 
Sorry, dann waren wir am Raum vorbei. 
nein, ich hab's noch nicht fixen können, das Problem. Meinst du du kannst heute um 15 Uhr in DM16?


Am Donnerstag, Juli 30, 2020 17:08 CEST, schrieb JirkaDellOro <notifications@github.com>:
 
 
ach wie doof, ich war in dm16, dem Spiellabor, das ist "mein" Raum...
Besteht das Problem noch?

**Comment by JirkaDellOro** [comment]
Funktioniert denn das hier bei dir? https://jirkadelloro.github.io/Prima/L12_Plattformer2D/

**Comment by sabinecelina** [comment]
Hab den Fehler jetzt gefunden. Danke.

Am Freitag, Juli 31, 2020 09:43 CEST, schrieb JirkaDellOro <notifications@github.com>:
 
 
Funktioniert denn das hier bei dir? https://jirkadelloro.github.io/Prima/L12_Plattformer2D/

**Comment by JirkaDellOro** [comment]
Was war's?

**Comment by sabinecelina** [comment]
lag an meinem server. irgendwann hab ich irgendwas eingestellt. habs jetzt über xampp laufen.

**Comment by JirkaDellOro** [comment]
Hmmm... vielleicht hattest Du die Firewall geschlossen
