### ISSUE TITLE
Probleme mit Kollisionen

### ISSUE THREAD

**Issue by LobinSan** [JirkaDellOro/Prima#41]
Hallo Jirka, 

ich habe über die letzten 4 Tage mit 4 meiner Kommilitonen, die an PRIMA Teilnehmen versucht meine Kollisionen zum laufen zu bekommen. Aber egal was ich auch mache, bei meinem Flappy-Birds-Klon wird durchgehend eine Kollision erkannt.
Ist es möglich, dass wir uns noch einmal über AlfaView meinen Code gemeinsam anschauen? 

Mein Code: https://github.com/LobinSan/PRIMA/tree/master/FlappyBox

Viele Grüße 
Robin Pittelkow

**Comment by JirkaDellOro** [comment]
Im Prinzip gerne, allerdings werde ich das wahrscheinlich nicht schaffen. Ich bin gerade sehr im Prüfungsstress. Wie prüfst Du die Kollisionen. In FUDGE/Test gibt es ein Beispiel für die Rectangle-Kollision.

**Comment by LobinSan** [comment]
Schade, ich habe sowohl aus deinen Beispielen die Kollisionsabfrage übernommen als auch eigene Möglichkeiten ausprobiert, jedoch bin ich zu keinem Funktionierenden Ergebnis gekommen.
