### ISSUE TITLE
shoot Methode

### ISSUE THREAD

**Issue by DavidNiemann** [JirkaDellOro/Prima#47]
https://github.com/DavidNiemann/PRIMA_Wi20/tree/main/L06_Doom
In der Avatar klasse ist die shoot Methode die wir geschrieben haben.
Ein Ray wird erstellt in Blickrichtung des Avatars und überprüft, ob ein Enemy getroffen wird. Bei mehreren Gegnern wird der vorderste getroffen, was in der Methode firstEnemy überprüft wird. Es wird überprüft dann überprüft, ob zwischen diesem Gegner eine Wand ist und wenn nicht wird er gelöscht. Zurzeit erschein noch eine Error, wenn kein Enemy mehr existiert

**Comment by JirkaDellOro** [comment]
Schicke bitte einen Screenshot der Fehlerausgabe und einen Link zu deiner Pages-Version, dann schaue ich mir das sehr gerne an.

**Comment by DavidNiemann** [comment]
Ich wollte nur den Anderen, die Nicht die ganzen Zeit da waren mitteilen, was wir noch zusammen im Unterricht zusammen programmiere heben als du weg musstest und habe dazugeschrieben das es ein Error gibt, dass es uns bewusst ist aber noch nicht dazukamen ihn zu fixen da wir schon überzogen hatten. Aber sollte kein Problem sein den zu beheben

**Comment by JirkaDellOro** [comment]
Achso
