### ISSUE TITLE
Rectangle bottom and top reversed

### ISSUE THREAD

**Issue by Oneof300** [JirkaDellOro/Prima#49]
Top and bottom are revesred, top returns the lower y-position and bottom the higher y-position.
Example:
let rect: ƒ.Rectangle = new ƒ.Rectangle(0, 0, 10, 10);
console.log("bottom:", rect.bottom, "top:", rect.top, "left:", rect.left, "right:", rect.right);
prints:
bottom: 10 top: 0 left: 0 right: 10

**Comment by JirkaDellOro** [comment]
Ja, in zweidimensionalen Räumen haben wir die Ecke meist links-oben. Die Designentscheidung für die FUDGE-Rectangles ist dorthin gefallen...

**Comment by JirkaDellOro** [comment]
Kann man den schließen?
