### ISSUE TITLE
Controller-Input?

### ISSUE THREAD

**Issue by AnnaLotz** [JirkaDellOro/Prima#5]
Hallo.
Gibt es in Fudge die Möglichkeit Controller-Inputs abzufangen?
Um mir die Steuerung und genauen Funktionen für mein 2,5D Platformer zu überlegen, wäre das gut zu wissen :)

**Comment by JirkaDellOro** [comment]
Es ist noch nichts speziell für FUDGE gebaut worden, wir müssten erst schauen, welche Funktionen über die Standard-Gamepad-API hinaus Sinn ergeben. Nimm also einfach diese:

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

**Comment by AnnaLotz** [comment]
Alles klar, danke für den Hinweis 👍
