### ISSUE TITLE
Kollisionsboxen werden nicht richtig mitrotiert

### ISSUE THREAD

**Issue by Oneof300** [JirkaDellOro/Prima#50]
Ich habe mehrere Knoten an einem Knoten "Platform", die mit der Plattform mitrotiert werden sollen. Diese Knoten haben Meshes und Rigidbodies. Während die Meshes der Kindknoten - beim manipulieren der Lokalen Matrix der Platform - vernünftig mitrotieren, weicht die Rotation der Kollisionsboxen ab, wie es durch Physics.settings.debugDraw zu sehen ist.

**Comment by JirkaDellOro** [comment]
Bitte Links zu Code und Runtime posten

**Comment by Oneof300** [comment]
https://github.com/Oneof300/MazeBall
Die html ist im Ordner "static" zu finden.

**Comment by JirkaDellOro** [comment]
Und zur App? Hast Du noch nicht auf Pages publiziert?

**Comment by Oneof300** [comment]
Bin daran, aber ich stoße da gerade noch auf Probleme.

**Comment by JirkaDellOro** [comment]
Spannender Fehler. OIMO nutzt gegenüber FUDGE die exakt umgekehrte Reihenfolge von Rotationen um eine Rotationsmatrix aus Eulerwinkeln zu berechnen. Ist erstmal gefixt und könnte noch optimiert werden. Bitte testen und ggf. schließen.

**Comment by Oneof300** [comment]
Ja klappt super! die Kollisionsboxen werden jetzt alle richtig mit rotiert, danke.
