### ISSUE TITLE
Formatierung von Attributen eigener Komponenten

### ISSUE THREAD

**Issue by Oneof300** [JirkaDellOro/Prima#52]
Attribute eigener Komponenten vom Typ number, werden im Editor direkt nebeneinander gereiht, anstatt untereinander angeordnet zu werden. Eventuell gilt das für alle Attribute, die in der Darstellung im Editor keine ganze Zeile einnehmen.

**Comment by JirkaDellOro** [comment]
Nein, war nur im Stylesheet nicht eingetragen. Müssen wir nun beobachten, ob es vielleicht an anderen Stellen zu unnötigen Zwischenräumen kommt.
