### ISSUE TITLE
Confusion with event system between different components

### ISSUE THREAD

**Issue by UmbertoFalkenhagen** [JirkaDellOro/Prima#56]
Hey, I've been trying to implement some simple event-handling between different components. My goal was to create a system in which my collision detector (placed respectively on each beam of every laser) would fire a collision event in case it collides with a agent. 

`if (posLocal.x <= (x) && posLocal.x >= -(x) && posLocal.y <= y && posLocal.y >= 0) {
        this.node.dispatchEvent(new CustomEvent("collisionEvent", { bubbles: true }));
        return true;
      } else {
        return false;
      }`

The event should travel up the hierarchy and until the listener in my main captures it and executes the hndCollisionEvent function.

`function hndCollisionEvent(_event: Event): void {
    console.log("Collision event received by", _event.currentTarget);
    graph.broadcastEvent(new CustomEvent("rotationChangeEvent"));
  }`

Until here the code works. However the rotationChangeEvent should then be broadcasted from here and listened to within the LaserRotator components (which are attached to the laser nodes) and if the beam that fired the original CollisionEvent is a child of that laser node it should rotate a little bit faster/slower or change its rotation direction (doesn't really matter its just to have something happening accordingly)

`public hndRotationChangeEvent(_event: Event): void {
      console.log("Rotation change event received by " + _event.currentTarget);
    }`

I tried different ways of creating the event listener (both of which did not work):
1. in the main when creating the different laser instances:
`copyLaser.addEventListener("rotationChangeEvent", copyLaser.getComponent(LaserRotator).hndRotationChangeEvent);`
or
2. within the LaserRotator components, similar to the component_add events:
`this.addEventListener("rotationChangeEvent", this.hndRotationChangeEvent);`

Now I have two questions: 
1. What do I have to change so that the broadcast event is being received properly?
2. How can I create the customevents in a way to easily attach the necessary information to them/How can I access the information properly when catching the event?

PS I tried looking for more information in fudges API reference but currently it doesnt seem to work for me (https://github.com/JirkaDellOro/FUDGE/issues/288)

PSS here is my Repo: https://github.com/UmbertoFalkenhagen/PRIMA-own

**Comment by JirkaDellOro** [comment]
1. Broadcasting an event sends them into the graph, they won't bubble back. A listener must listen in the capture phase.
2. For Custom data, use `detail`, see the regular documentations for DOM-Events.
3. Only events specific for components are automatically send to components attached. The regular pattern is to install the listener to the node! You can do that from the component though, when it's being attached, and should be removed when the component gets removed.

**Comment by JirkaDellOro** [comment]
Ist das geklärt oder soll hier etwas gemacht werden?
