### ISSUE TITLE
Coat issues

### ISSUE THREAD

**Issue by UmbertoFalkenhagen** [JirkaDellOro/Prima#58]
I ran into some issues with materials.
I set up a completely new project (https://github.com/UmbertoFalkenhagen/Prima/tree/master/projects/Pacman), then I added a grapp, a mesh and a unicolor material and combined them to have a proper scene graph. However, when running the project it prompts the error shown in the screenshot. Any clues what might be causing this?

(btw in the editor the material and mesh are shown properly)
![image](https://user-images.githubusercontent.com/48802310/159273630-44c783c4-8c60-40b8-860b-73da3b7f1edc.png)

**Comment by JirkaDellOro** [comment]
Old version, I assume. There is no getCoat()-Method anymore, just coat, and CoatUnicolor is now CoatLit. Your editor appears to generate data which the current version does not interpret anymore.

**Comment by UmbertoFalkenhagen** [comment]
i pulled the current version of fudge before stting up the project. so maybe the getCoat() functions are still called somewhere in the code...

**Comment by JirkaDellOro** [comment]
That would be quite a surprise. Did you pull from a branch other than development?

**Comment by UmbertoFalkenhagen** [comment]
I did it by forking your prima repo (did that last semester already) and pulling your latest updates. last semester this worked without issues, did anything change about that?

**Comment by JirkaDellOro** [comment]
You also need a current editor!

**Comment by UmbertoFalkenhagen** [comment]
Yeah that did the trick! It works now, thanks a lot! :) Issue closed.
