### ISSUE TITLE
Sprite Animation Standbild

### ISSUE THREAD

**Issue by KohlerAl** [JirkaDellOro/Prima#59]
Hallo, ich hab ein Problem mit der Animation von den Spritesheets. Mit manchen Bildern funktioniert die Animation, mit anderen bekomme ich nur ein Standbild und ich erkenne kein Muster warum es manchmal geht und manchmal nicht. Hier sind die Links auf meine Anwendung: https://kohleral.github.io/PRIMA/Super_Mario/index.html
https://github.com/KohlerAl/PRIMA/tree/main/Super_Mario

Mit texture.png hab ich es hinbekommen, das ist das Spritesheet von Pacman. Mit Ghosty_Hat (einem Teilbild von dem Pacman-Spritesheet) geht es nicht. Und halt auch nicht mit meinen Mario Sprites :( 

Der Code ist der aus der Veranstaltung und wie gesagt mit manchen Bildern geht er ja auch. Es ist wahrscheinlich irgendwas dummes, aber ich komm einfach nicht drauf woran es liegen könnte. Ich hoffe mir kann jemand weiterhelfen :)

**Comment by JirkaDellOro** [comment]
So wie ich es sehe, ist derzeit nur Mario da und ich debugge nur ein Sprite. Korrekt?

In Zeile 60 von Aid.NodeSprite 
`this.frameCurrent = (this.frameCurrent + this.direction + this.animation.frames.length) % this.animation.frames.length;`
sehe ich das this.animation.frames.length den Wert 1 hat, also nur 1 Frame angelegt ist.

**Comment by JirkaDellOro** [comment]
Das sieht man aber auch schon in deiner Konsolenausgabe, also nichts Neues...
Dort sieht man, dass dein Spritesheet 504x73 groß zu sein scheint, deine _position beginnt aber bei 818, das passt nicht zusammen.

**Comment by KohlerAl** [comment]
Oh man, ich wusste es ist irgendeine Kleinigkeit. Es funktioniert jetzt mit einem kleineren Wert auf jeden Fall, Danke. Ich hab da am Mittwoch so viel rumprobiert und Werte geändert, dass ich gar nicht mehr weiß was ich am Anfang für Werte mit welchem Bild hatte. Ich weiß nur dass mein Original eine höhere Auflösung hatte, ich hatte dann aber das Bild selbst auch im Verdacht und hab da verschiedene Varianten exportiert.
