### ISSUE TITLE
Localhost Server

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/Prima#6]
Hallo Jirka, 
ich wollte dein Spritesheet testen. 

Leider sehe ich die Spritesheet Animation von dir mit der Go Live Extension von VSC nicht.
In der Console wird mir auch kein Fehler angezeigt. [Screenshot](https://webuser.hs-furtwangen.de/~gretherb/prima/Screenshot%202020-01-08%20at%2009.48.27.png)

Nun wollte ich das über Serve Testen.

Serve ist bei mir in der v.6.11.3 installiert. 
Jetzt ist meine Frage damit ich es starten kann. Brauch ich noch ne json File ? Oder was muss ich Eingeben das ich es starten kann? Stehe gerade einfach auf dem Schlauch. 

Viele Grüße
Benedikt

**Comment by JirkaDellOro** [comment]
Die Meldung ist leider wenig aussagekräftig. Komm' mal bitte mit deinem Rechner im Spiellabor vorbei

**Comment by benediktgrether** [comment]
Bin leider heute nicht in Furtwangen. Wir müssten morgen das Problem kurz angehen. Ich werde es heute Abend noch am großen Display und mit Firefox testen.

Ab wann bist du morgen im Spiellabor?

**Comment by JirkaDellOro** [comment]
ab 8.30 Uhr

**Comment by JirkaDellOro** [comment]
Haben wir das geklärt? Dann bitte schließen....
