### ISSUE TITLE
Documentation auf der Kursseite

### ISSUE THREAD

**Issue by MarkusDamm** [JirkaDellOro/Prima#61]
Ich fand es öfter schon sehr hilfreich, wenn die Dokus für Fudge (Core, Aid, usw.) auf der Kursseite verlinkt werden würden. Gerade meintest Du Jirka, ich solle den Issue anlegen, weil das eine gute Idee war. 

Das hat mich sehr gefreut zu hören

**Comment by JirkaDellOro** [comment]
Es gibt jetzt einen Link zu den Runtime-Pages, unten sind da die Links
