### ISSUE TITLE
Page wont deplay Subfolder

### ISSUE THREAD

**Issue by ArthurErlich** [JirkaDellOro/Prima#63]
I found out why certain subfolder won't deploy on GitHub Pages!
[Link to thread](https://github.com/orgs/community/discussions/22161#discussioncomment-3235706)

**Comment by JirkaDellOro** [comment]
Classic. That happens when information for one purpose (identifying a folder) is used for an obscure other purpose (exclude from processing). That's a fundamental software design flaw, but so common. Please never do that!
