### ISSUE TITLE
Internal folder view not updating

### ISSUE THREAD

**Issue by ArthurErlich** [JirkaDellOro/Prima#64]
I got the latest Fudge build and when I add something from the external source, the internal source folder is not updating.
![image](https://user-images.githubusercontent.com/92059317/226436080-4083a645-8261-44ea-87a2-9ea2aee10089.png)
It updates after saving and loading.

**Comment by JirkaDellOro** [comment]
Should be fixed now, please test and close issue if applicable. Was the same problem with the external window, forgotten events after refactoring message pump.

**Comment by ArthurErlich** [comment]
Looks like it works now, thanks!
![FUDGE_Internal_Works](https://user-images.githubusercontent.com/92059317/226545136-513c487c-6a7d-4460-ad31-bc90ad9690af.gif)
