### ISSUE TITLE
[Suggestion]: Adding a way to structure the internal source folder

### ISSUE THREAD

**Issue by ArthurErlich** [JirkaDellOro/Prima#65]
It would be nice if we could sort the internal source folder. A good idea would be to have the possibility to add folders to drag and drop the files/meshes/groupse inside.

**Comment by Plagiatus** [comment]
I know this issue is over a year old, but just letting you know that FUDGE has that feature now. 😄

**Comment by ArthurErlich** [comment]
Thanks! :) 
I may update my HomeFuge to the current Fudge Version
