### ISSUE TITLE
Craftris - Verbesserung der Steuerung

### ISSUE THREAD

**Issue by benediktgrether** [JirkaDellOro/Prima#7]
Hallo Jirka, 
wie gestern angesprochen hier ein Issue zum Vorschlag der Verbesserung der Steuerung von Craftris.

Die Hoch und Runterbewegung durch die Verknüpfung von Shift + W / S. 

<s>Ein weiterer Vorschlag von mir. 
Wie wär es wenn die Kamera bestimmte Winkel überschreitet das die Steuerung Invertiert wird? Damit meine ich, wenn man die Camera auf der Horizontale um 180° Dreht dass dann die Links und Rechts bewegung Invertiert wird, damit Sie wieder richtig funktioniert. Genau so wenn man auf der Vertikal eine Winkel überschreitet das dann die Bewegung wo falsch ist auch invertiert. </s>

Viele Grüße
Benedikt

**Comment by JirkaDellOro** [comment]
Überprüfe das mit der Anpassung der Steuerung an die Camera noch einmal, es ist eigentlich implementiert für 90°-Segmente des Orbits.

**Comment by JirkaDellOro** [comment]
Schon überprüft? Manchmal scheint es mit der Transformation der Steuerung nicht zu klappen. Wenn Du herausfinden könntest, wie man den Fehler reproduziert, wäre ich dankbar.

**Comment by benediktgrether** [comment]
Ich hatte noch keine Zeit es zu testen. Werde es jetzt aber paar mal probieren.

**Comment by benediktgrether** [comment]
Ich hab es gerade mehrmals getestet. 3 von 5 Spielen hatte ich Probleme mit der Steuerung. 

Als es beim zweiten mal aufgetaucht ist. Hatte ich das Gefühl das es von der Rotation eines Fragmentes herkommt. Hab es paar mal hin und her Rotiert um zu schauen wie es passt und danach kam es wieder zu Probleme mit der Steuerung.
 
Beim 3 Spiel ist es wieder aufgetaucht. Ich habe wieder das Fragment hin und her rotiert und es lag dabei schon mit einer Kante an bestehenden Cuben die ich platziert hatte im Spiel. Vielleicht ist das des Problem das es dann zur Fehlern in der Transformation der Steuerung kommt.

**Comment by JirkaDellOro** [comment]
Also ohne dass Du die Kamera bewegt hast?

**Comment by benediktgrether** [comment]
Tut mir leid, das hab ich vergessen zu Kommunizieren. Die Kamera hab ich auch Rotiert dabei.

**Comment by JirkaDellOro** [comment]
Hallo Benedikt,

bitte spiele mein GlobalGameJam-Projekt: https://jirkadelloro.github.io/Episoma/
und prüfe, ob die Steuerung dir besser zusagt.

PS: Gewinnbedingung wird noch nicht geprüft, Du musst deinen intrinsisch motivierten Dopaminausstoß genießen, wenn Du den Würfel wieder zusammengesetzt hast.

**Comment by benediktgrether** [comment]
Hallo Jirka, ich werde es bei Gelegenheit Testen und dir noch mal Rückmeldung geben.

Viele Grüße Benedikt
